/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: sksourou <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2015/01/27 04:40:56 by sksourou          #+#    #+#             */
/*   Updated: 2015/03/02 17:32:33 by lubaujar         ###   ########.fr       */
/*   Updated: 2015/02/20 07:25:22 by lubaujar         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "printf.h"
#include <limits.h>
#include <locale.h>

int		main(void)
{
	//int				i;
	//unsigned int	l;
//	char			*str;



	printf("\nret: %d", ft_printf("%s %C %d %p %x %% %S", "bonjour ", L'該', 42, &free, 42, L"لحم خن"));
	/*ft_print, f("%-d\n", 42);
	ft_printf("%+d\n", 42);
	ft_printf("% d\n", 42);
	ft_printf("%#d\n", 42);
	ft_printf("%-21d\n", 42);
	ft_printf("%+21d\n", 42);
	ft_printf("% 21d\n", 42);
	ft_printf("%#21d\n", 42);*/
/*	char* l = setlocale(LC_ALL, "");

	if (l == NULL)
		printf("Locale not set\n");
	else
	printf("Locale set to %s\n", l);
	ft_printf("%lc%lc", 0, 42);
	printf("Locale set to %s\n", l);
	printf("{% S}", L"");
	ft_printf("{% S}", L"");*/
//	ft_printf("{%03.2d}", 0);
//	ft_printf("{%03d}", 0);
	
	//printf("ret: %d\n", ft_printf("%s %C %d %p %x %% %S", "bonjour ", L'該', 42, &free, 42, L"لحم خنزير"));
//	ft_printf("%S", L"我是一只猫。");
	/*printf("ret: %d\n", ft_printf("....%swith string\n", "lala"));
	printf("ret: %d\n", printf("....%swith string\n", "lala"));
	printf("ret: %d\n", ft_printf("%s\n", "abc"));
	printf("ret: %d\n", printf("%s\n", "abc"));
	printf("ret: %d\n", ft_printf("111 %s 333\n", "222"));
	printf("ret: %d\n", printf("111 %s 333\n", "222"));*/
//	printf("%p\n", 0);
	//printf("|%-     20Z|\n");
	//ft_printf("{%-15Z}");
	//printf("%.3%");
//	printf("{%05.c}", 0);
//	ft_printf("%s %C %d %p %x %% %S", "bonjour ", L'該', 42, &free, 42, L"لحم خن");
/*	printf("  [%d]\n", printf("%C\n", L'α'));
	printf("  [%d]\n", printf("%C\n", L'米'));
	printf("  [%d]\n", printf("%C\n", L'요'));
	printf("  [%d]\n", printf("%C\n", L'莨'));
	ft_printf("%C\n", L'α');
	ft_printf("%C\n", L'米');
	ft_printf("%C\n", L'요');
	ft_printf("%C\n", L'莨');*/
	//printf("  [%d]\n", printf("%S\n", L"一"));
	//ft_printf("%S\n", L"一");
//	printf("  [%d]\n", printf("%C\n", L'一'));
//	ft_printf("%C\n", L'一');
//	printf("  [%d]\n", printf("%C\n",L'只'));
//	ft_printf("%C\n",L'只');
/*	printf("  [%d]\n", printf("%S\n", L"α"));
	ft_printf("%S\n", L"α");
	printf("  [%d]\n", printf("%S\n", L"αα"));
	ft_printf("%S\n", L"αα");*/
//	ft_printf("%C\n", L'a');
	/*printf("{%05.c}", 0);
	printf("\n");
	ft_printf("{%05.c}", 0);
	printf("\n");*/
//	ft_printf("111%s333\n", "222");
/*	ft_printf("[infos] %d %i %s %p\n", 0, 0, "babaauwhum", &str);
	printf("\n");
	ft_printf("[infos] %d %i %s %p\n", 0, 0, "babaauwhum", &str);*/
/*
	printf("\t\t\t->[ %s%%d%s ]<-\n", BOLD_LIGHT_GREY, END);
	printf("\t\t\t [ %sMODIF%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][d]\t%s-->%s|%d|\n", BOLD_RED, END, INT_MAX);
	ft_printf("\t[d]\t%s-->%s|%d|\n", BOLD_GREEN, END, INT_MAX);
	printf("[printf][d]\t%s-->%s|%d|\n", BOLD_RED, END, INT_MIN);
	ft_printf("\t[d]\t%s-->%s|%d|\n", BOLD_GREEN, END, INT_MIN);
	printf("[printf][hd]\t%s-->%s|%hd|\n", BOLD_RED, END, SHRT_MAX);
	ft_printf("\t[hd]\t%s-->%s|%hd|\n", BOLD_GREEN, END, SHRT_MAX);
	printf("[printf][hd]\t%s-->%s|%hd|\n", BOLD_RED, END, SHRT_MIN);
	ft_printf("\t[hd]\t%s-->%s|%hd|\n", BOLD_GREEN, END, SHRT_MIN);
	printf("[printf][hhd]\t%s-->%s|%hhd|\n", BOLD_RED, END, SCHAR_MAX);
	ft_printf("\t[hhd]\t%s-->%s|%hhd|\n", BOLD_GREEN, END, SCHAR_MAX);
	printf("[printf][hhd]\t%s-->%s|%hhd|\n", BOLD_RED, END, SCHAR_MIN);
	ft_printf("\t[hhd]\t%s-->%s|%hhd|\n", BOLD_GREEN, END, SCHAR_MIN);
	printf("[printf][ld]\t%s-->%s|%ld|\n", BOLD_RED, END, LONG_MAX);
	ft_printf("\t[ld]\t%s-->%s|%ld|\n", BOLD_GREEN, END, LONG_MAX);
	printf("[printf][ld]\t%s-->%s|%ld|\n", BOLD_RED, END, LONG_MIN);
	ft_printf("\t[ld]\t%s-->%s|%ld|\n", BOLD_GREEN, END, LONG_MIN);
	printf("[printf][lld]\t%s-->%s|%lld|\n", BOLD_RED, END, LLONG_MAX);
	ft_printf("\t[lld]\t%s-->%s|%lld|\n", BOLD_GREEN, END, LLONG_MAX);
	printf("[printf][lld]\t%s-->%s|%lld|\n", BOLD_RED, END, LLONG_MIN);
	ft_printf("\t[lld]\t%s-->%s|%lld|\n", BOLD_GREEN, END, LLONG_MIN);
	printf("[printf][jd]\t%s-->%s|%jd|\n", BOLD_RED, END, LLONG_MAX);
	ft_printf("\t[jd]\t%s-->%s|%jd|\n", BOLD_GREEN, END, LLONG_MAX);
	printf("[printf][jd]\t%s-->%s|%jd|\n", BOLD_RED, END, LLONG_MIN);
	ft_printf("\t[jd]\t%s-->%s|%jd|\n", BOLD_GREEN, END, LLONG_MIN);
	printf("\t\t\t [ %s.PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][d]\t%s-->%s|%.0d|\n", BOLD_RED, END, 42);
	ft_printf("\t[d]\t%s-->%s|%.0d|\n", BOLD_GREEN, END, 42);
	printf("[printf][d]\t%s-->%s|%.1d|\n", BOLD_RED, END, 42);
	ft_printf("\t[d]\t%s-->%s|%.1d|\n", BOLD_GREEN, END, 42);
	printf("[printf][d]\t%s-->%s|%.0d|\n", BOLD_RED, END, 0);
	ft_printf("\t[d]\t%s-->%s|%.0d|\n", BOLD_GREEN, END, 0);
	printf("[printf][d]\t%s-->%s|%.1d|\n", BOLD_RED, END, 0);
	ft_printf("\t[d]\t%s-->%s|%.1d|\n", BOLD_GREEN, END, 0);
	printf("[printf][d]\t%s-->%s|%.7d|\n", BOLD_RED, END, 42);
	ft_printf("\t[d]\t%s-->%s|%.7d|\n", BOLD_GREEN, END, 42);
	printf("[printf][d]\t%s-->%s|%.7d|\n", BOLD_RED, END, -42);
	ft_printf("\t[d]\t%s-->%s|%.7d|\n", BOLD_GREEN, END, -42);
	printf("[printf][d]\t%s-->%s|%.21d|\n", BOLD_RED, END, 42);
	ft_printf("\t[d]\t%s-->%s|%.21d|\n", BOLD_GREEN, END, 42);
	printf("[printf][d]\t%s-->%s|%.21d|\n", BOLD_RED, END, -42);
	ft_printf("\t[d]\t%s-->%s|%.21d|\n", BOLD_GREEN, END, -42);
	printf("\t\t\t [ %sWIDTH%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][d]\t%s-->%s|%1d|\n", BOLD_RED, END, 42);
	ft_printf("\t[d]\t%s-->%s|%1d|\n", BOLD_GREEN, END, 42);
	printf("[printf][d]\t%s-->%s|%1d|\n", BOLD_RED, END, -42);
	ft_printf("\t[d]\t%s-->%s|%1d|\n", BOLD_GREEN, END, -42);
	printf("[printf][d]\t%s-->%s|%1d|\n", BOLD_RED, END, 0);
	ft_printf("\t[d]\t%s-->%s|%1d|\n", BOLD_GREEN, END, 0);
	printf("[printf][d]\t%s-->%s|%10d|\n", BOLD_RED, END, 0);
	ft_printf("\t[d]\t%s-->%s|%10d|\n", BOLD_GREEN, END, 0);
	printf("[printf][d]\t%s-->%s|%21d|\n", BOLD_RED, END, 42);
	ft_printf("\t[d]\t%s-->%s|%21d|\n", BOLD_GREEN, END, 42);
	printf("[printf][d]\t%s-->%s|%21d|\n", BOLD_RED, END, -42);
	ft_printf("\t[d]\t%s-->%s|%21d|\n", BOLD_GREEN, END, -42);
	printf("[printf][d]\t%s-->%s|%42d|\n", BOLD_RED, END, 42);
	ft_printf("\t[d]\t%s-->%s|%42d|\n", BOLD_GREEN, END, 42);
	printf("[printf][d]\t%s-->%s|%42d|\n", BOLD_RED, END, -42);
	ft_printf("\t[d]\t%s-->%s|%42d|\n", BOLD_GREEN, END, -42);
	printf("\t\t     [ %sWIDTH + .PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][d]\t%s-->%s|%1.0d|\n", BOLD_RED, END, 42);
	ft_printf("\t[d]\t%s-->%s|%1.0d|\n", BOLD_GREEN, END, 42);
	printf("[printf][d]\t%s-->%s|%1.0d|\n", BOLD_RED, END, -42);
	ft_printf("\t[d]\t%s-->%s|%1.0d|\n", BOLD_GREEN, END, -42);
	printf("[printf][d]\t%s-->%s|%10.2d|\n", BOLD_RED, END, 42);
	ft_printf("\t[d]\t%s-->%s|%10.2d|\n", BOLD_GREEN, END, 42);
	printf("[printf][d]\t%s-->%s|%10.2d|\n", BOLD_RED, END, -42);
	ft_printf("\t[d]\t%s-->%s|%10.2d|\n", BOLD_GREEN, END, -42);
	printf("[printf][d]\t%s-->%s|%10.6d|\n", BOLD_RED, END, -42);
	ft_printf("\t[d]\t%s-->%s|%10.6d|\n", BOLD_GREEN, END, -42);
	printf("[printf][d]\t%s-->%s|%42.21d|\n", BOLD_RED, END, INT_MAX);
	ft_printf("\t[d]\t%s-->%s|%42.21d|\n", BOLD_GREEN, END, INT_MAX);
	printf("[printf][d]\t%s-->%s|%42.21d|\n", BOLD_RED, END, INT_MIN);
	ft_printf("\t[d]\t%s-->%s|%42.21d|\n", BOLD_GREEN, END, INT_MIN);
	printf("[printf][d]\t%s-->%s|%26.24d|**|%26.24d|\n", BOLD_RED, END, INT_MAX, INT_MIN);
	ft_printf("\t[d]\t%s-->%s|%26.24d|**|%26.24d|\n", BOLD_GREEN, END, INT_MAX, INT_MIN);
	printf("\t\t\t [ %sSPACE%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][d]\t%s-->%s|% d|\n", BOLD_RED, END, 42);
	ft_printf("\t[d]\t%s-->%s|% d|\n", BOLD_GREEN, END, 42);
	printf("[printf][d]\t%s-->%s|% d|\n", BOLD_RED, END, -42);
	ft_printf("\t[d]\t%s-->%s|% d|\n", BOLD_GREEN, END, -42);
	printf("[printf][d]\t%s-->%s|% d|\n", BOLD_RED, END, INT_MAX);
	ft_printf("\t[d]\t%s-->%s|% d|\n", BOLD_GREEN, END, INT_MAX);
	printf("[printf][d]\t%s-->%s|% d|\n", BOLD_RED, END, INT_MIN);
	ft_printf("\t[d]\t%s-->%s|% d|\n", BOLD_GREEN, END, INT_MIN);
	printf("[printf][d]\t%s-->%s|wesh % d bico|\n", BOLD_RED, END, 42);
	ft_printf("\t[d]\t%s-->%s|wesh % d bico|\n", BOLD_GREEN, END, 42);

	printf("\n%s----------------------------------------------------%s", LIGHT_GREY, END);
	printf("\n%s----------------------------------------------------%s\n\n", LIGHT_GREY, END);

	printf("\t\t\t->[ %s%%s%s ]<-\n", BOLD_LIGHT_GREY, END);
	printf("\t\t\t[ %sBASIC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][s]\t%s-->%s|%s|\n", BOLD_RED, END, "abcde");
	ft_printf("\t[s]\t%s-->%s|%s|\n", BOLD_GREEN, END, "abcde");
	printf("[printf][s]\t%s-->%s|!!%s!!|\n", BOLD_RED, END, "??");
	ft_printf("\t[s]\t%s-->%s|!!%s!!|\n", BOLD_GREEN, END, "??");
	printf("[printf][s]\t%s-->%s|%s|\n", BOLD_RED, END, 0);
	ft_printf("\t[s]\t%s-->%s|%s|\n", BOLD_GREEN, END, 0);
	printf("[printf][s]\t%s-->%s|%s|\n", BOLD_RED, END, "");
	ft_printf("\t[s]\t%s-->%s|%s|\n", BOLD_GREEN, END, "");
	printf("[printf][s]\t%s-->%s|!!%s!!%s!!!%s!!!!|\n", BOLD_RED, END, "??", "???", "????");
	ft_printf("\t[s]\t%s-->%s|!!%s!!%s!!!%s!!!!|\n", BOLD_RED, END, "??", "???", "????");
	printf("\t\t\t[ %s.PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][s]\t%s-->%s|%.1s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%.1s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%.10s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%.10s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%.42s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%.42s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%.4s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%.4s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%.2s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%.2s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("\t\t\t[ %sWIDTH%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][s]\t%s-->%s|%1s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%1s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%10s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%10s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%42s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%42s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%13s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%13s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("\t\t     [ %sWIDTH + .PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][s]\t%s-->%s|%1.1s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%1.1s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%10.1s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%10.1s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%10.10s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%10.10s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%42.21s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%42.21s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%3.21s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%3.21s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%10.21s|\n", BOLD_RED, END, "");
	ft_printf("\t[s]\t%s-->%s|%10.21s|\n", BOLD_GREEN, END, "");
	printf("[printf][s]\t%s-->%s|%21.12s|\n", BOLD_RED, END, "42");
	ft_printf("\t[s]\t%s-->%s|%21.12s|\n", BOLD_GREEN, END, "42");
	printf("\t\t\t[ %sFLAG -%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][s]\t%s-->%s|%-s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%-s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%-21s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%-21s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%-.4s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%-.4s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%-21.4s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%-21.4s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%-42.21s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%-42.21s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("\t\t\t[ %sFLAG 0%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][s]\t%s-->%s|%0s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%0s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%021s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%021s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%0.4s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%0.4s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%021.4s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%021.4s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("[printf][s]\t%s-->%s|%042.21s|\n", BOLD_RED, END, "Baba Au Whum");
	ft_printf("\t[s]\t%s-->%s|%042.21s|\n", BOLD_GREEN, END, "Baba Au Whum");
	printf("\t\t\t[ %sBONUS%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][s]\t%s-->%s|%s|\n", BOLD_RED, END, "Y0ja on t'encule =D");
	ft_printf("\t[s]\t%s-->%s|%0s|\n", BOLD_GREEN, END, "Y0ja on t'encule =D");

	printf("\n%s----------------------------------------------------%s", LIGHT_GREY, END);
	printf("\n%s----------------------------------------------------%s\n\n", LIGHT_GREY, END);

	printf("\t\t\t->[ %s%%p%s ]<-\n", BOLD_LIGHT_GREY, END);
	printf("\t\t\t[ %sBASIC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][p]\t%s-->%s|%p|\n", BOLD_RED, END, &i);
	ft_printf("\t[p]\t%s-->%s|%p|\n", BOLD_GREEN, END, &i);
	printf("[printf][p]\t%s-->%s|%p|\n", BOLD_RED, END, &l);
	ft_printf("\t[p]\t%s-->%s|%p|\n", BOLD_GREEN, END, &l);
	printf("[printf][p]\t%s-->%s|%p|\n", BOLD_RED, END, &str);
	ft_printf("\t[p]\t%s-->%s|%p|\n", BOLD_GREEN, END, &str);
	printf("[printf][p]\t%s-->%s|%p|\n", BOLD_RED, END, 0);
	ft_printf("\t[p]\t%s-->%s|%p|\n", BOLD_GREEN, END, 0);
	printf("\t\t\t[ %s.PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][p]\t%s-->%s|%.1p|\n", BOLD_RED, END, &i);
	ft_printf("\t[p]\t%s-->%s|%.1p|\n", BOLD_GREEN, END, &i);
	printf("[printf][p]\t%s-->%s|%.21p|\n", BOLD_RED, END, &i);
	ft_printf("\t[p]\t%s-->%s|%.21p|\n", BOLD_GREEN, END, &i);
	printf("[printf][p]\t%s-->%s|%.12p|\n", BOLD_RED, END, &str);
	ft_printf("\t[p]\t%s-->%s|%.12p|\n", BOLD_GREEN, END, &str);
	printf("[printf][p]\t%s-->%s|%.21p|\n", BOLD_RED, END, &str);
	ft_printf("\t[p]\t%s-->%s|%.21p|\n", BOLD_GREEN, END, &str);
	printf("[printf][p]\t%s-->%s|%.21p|\n", BOLD_RED, END, 0);
	ft_printf("\t[p]\t%s-->%s|%.21p|\n", BOLD_GREEN, END, 0);
	printf("\t\t\t[ %sWIDTH%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][p]\t%s-->%s|%1p|\n", BOLD_RED, END, &i);
	ft_printf("\t[p]\t%s-->%s|%1p|\n", BOLD_GREEN, END, &i);
	printf("[printf][p]\t%s-->%s|%21p|\n", BOLD_RED, END, &i);
	ft_printf("\t[p]\t%s-->%s|%21p|\n", BOLD_GREEN, END, &i);
	printf("[printf][p]\t%s-->%s|%1p|\n", BOLD_RED, END, &str);
	ft_printf("\t[p]\t%s-->%s|%1p|\n", BOLD_GREEN, END, &str);
	printf("[printf][p]\t%s-->%s|%42p|\n", BOLD_RED, END, &str);
	ft_printf("\t[p]\t%s-->%s|%42p|\n", BOLD_GREEN, END, &str);
	printf("[printf][p]\t%s-->%s|%21p|\n", BOLD_RED, END, 0);
	ft_printf("\t[p]\t%s-->%s|%21p|\n", BOLD_GREEN, END, 0);
	printf("\t\t     [ %sWIDTH + .PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][p]\t%s-->%s|%1.1p|\n", BOLD_RED, END, &i);
	ft_printf("\t[p]\t%s-->%s|%1.1p|\n", BOLD_GREEN, END, &i);
	printf("[printf][p]\t%s-->%s|%21.3p|\n", BOLD_RED, END, &i);
	ft_printf("\t[p]\t%s-->%s|%21.3p|\n", BOLD_GREEN, END, &i);
	printf("[printf][p]\t%s-->%s|%1.21p|\n", BOLD_RED, END, &str);
	ft_printf("\t[p]\t%s-->%s|%1.21p|\n", BOLD_GREEN, END, &str);
	printf("[printf][p]\t%s-->%s|%42.21p|\n", BOLD_RED, END, &str);
	ft_printf("\t[p]\t%s-->%s|%42.21p|\n", BOLD_GREEN, END, &str);
	printf("[printf][p]\t%s-->%s|%21.12p|\n", BOLD_RED, END, 0);
	ft_printf("\t[p]\t%s-->%s|%21.12p|\n", BOLD_GREEN, END, 0);

	printf("\n%s----------------------------------------------------%s", LIGHT_GREY, END);
	printf("\n%s----------------------------------------------------%s\n\n", LIGHT_GREY, END);

	printf("\t\t\t->[ %s%%c%s ]<-\n", BOLD_LIGHT_GREY, END);
	printf("\t\t\t[ %sBASIC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][c]\t%s-->%s|%c|\n", BOLD_RED, END, '0');
	ft_printf("\t[c]\t%s-->%s|%c|\n", BOLD_GREEN, END, '0');
	printf("[printf][c]\t%s-->%s|%c|\n", BOLD_RED, END, '4');
	ft_printf("\t[c]\t%s-->%s|%c|\n", BOLD_GREEN, END, '4');
	printf("[printf][c]\t%s-->%s|%c|\n", BOLD_RED, END, '2');
	ft_printf("\t[c]\t%s-->%s|%c|\n", BOLD_GREEN, END, '2');
	printf("[printf][c]\t%s-->%s|%c|\n", BOLD_RED, END, 0);
	ft_printf("\t[c]\t%s-->%s|%c|\n", BOLD_GREEN, END, 0);
	printf("\t\t\t[ %sBONUS%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][c]\t-->|(.%c.)|\n", 'y');
	ft_printf("\t[c]\t-->|(.%c.)|\n", 'y');
	printf("[printf][c]\t-->|(.%c.) ** (.%c.)|\n", 'y', 'y');
	ft_printf("\t[c]\t-->|(.%c.) ** (.%c.)|\n", 'y', 'y');
	printf("[printf][c]\t-->|[%c%c]|\n", '4', '2');
	ft_printf("\t[c]\t-->|[%c%c]|\n", '4', '2');
	printf("[printf][c]\t-->|(.%c.) ** (.%c.) ** [%c%c]|\n", 'y', 'y', '4', '2');
	ft_printf("\t[c]\t-->|(.%c.) ** (.%c.) ** [%c%c]|\n", 'y', 'y', '4', '2');

	printf("\n%s----------------------------------------------------%s", LIGHT_GREY, END);
	printf("\n%s----------------------------------------------------%s\n\n", LIGHT_GREY, END);

	printf("\t\t\t->[ %s%%u%s ]<-\n", BOLD_LIGHT_GREY, END);
	printf("\t\t\t[ %sBASIC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][u]\t%s-->%s|%u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%u|\n", BOLD_RED, END, UINT_MAX);
	ft_printf("\t[u]\t%s-->%s|%u|\n", BOLD_GREEN, END, UINT_MAX);
	printf("[printf][u]\t%s-->%s|%u|\n", BOLD_RED, END, 0);
	ft_printf("\t[u]\t%s-->%s|%u|\n", BOLD_GREEN, END, 0);
	printf("\t\t\t[ %sMODIF%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][hu]\t%s-->%s|%hu|\n", BOLD_RED, END, USHRT_MAX);
	ft_printf("\t[hu]\t%s-->%s|%hu|\n", BOLD_GREEN, END, USHRT_MAX);
	printf("[printf][hhu]\t%s-->%s|%hhu|\n", BOLD_RED, END, UCHAR_MAX);
	ft_printf("\t[hhu]\t%s-->%s|%hhu|\n", BOLD_GREEN, END, UCHAR_MAX);
	printf("[printf][lu]\t%s-->%s|%lu|\n", BOLD_RED, END, ULONG_MAX);
	ft_printf("\t[lu]\t%s-->%s|%lu|\n", BOLD_GREEN, END, ULONG_MAX);
	printf("[printf][llu]\t%s-->%s|%llu|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[llu]\t%s-->%s|%llu|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t\t[ %s.PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][u]\t%s-->%s|%.0u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%.0u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%.1u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%.1u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%.0u|\n", BOLD_RED, END, 0);
	ft_printf("\t[u]\t%s-->%s|%.0u|\n", BOLD_GREEN, END, 0);
	printf("[printf][u]\t%s-->%s|%.1u|\n", BOLD_RED, END, 0);
	ft_printf("\t[u]\t%s-->%s|%.1u|\n", BOLD_GREEN, END, 0);
	printf("[printf][u]\t%s-->%s|%.7u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%.7u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%.21u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%.21u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%.21u|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[u]\t%s-->%s|%.21u|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t\t[ %sWIDTH%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][u]\t%s-->%s|%1u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%1u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%10u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%10u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%1u|\n", BOLD_RED, END, 0);
	ft_printf("\t[u]\t%s-->%s|%1u|\n", BOLD_GREEN, END, 0);
	printf("[printf][u]\t%s-->%s|%10u|\n", BOLD_RED, END, 0);
	ft_printf("\t[u]\t%s-->%s|%10u|\n", BOLD_GREEN, END, 0);
	printf("[printf][u]\t%s-->%s|%7u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%7u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%21u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%21u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%21u|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[u]\t%s-->%s|%21u|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t     [ %sWIDTH + .PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][u]\t%s-->%s|%1.0u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%1.0u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%10.1u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%10.1u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%1.1u|\n", BOLD_RED, END, 0);
	ft_printf("\t[u]\t%s-->%s|%1.1u|\n", BOLD_GREEN, END, 0);
	printf("[printf][u]\t%s-->%s|%10.2u|\n", BOLD_RED, END, 0);
	ft_printf("\t[u]\t%s-->%s|%10.2u|\n", BOLD_GREEN, END, 0);
	printf("[printf][u]\t%s-->%s|%7.4u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%7.4u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%42.21u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%42.21u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%21.7u|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[u]\t%s-->%s|%21.7u|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("[printf][u]\t%s-->%s|%10.21u|\n", BOLD_RED, END, 42);
	ft_printf("\t[u]\t%s-->%s|%10.21u|\n", BOLD_GREEN, END, 42);
	printf("[printf][u]\t%s-->%s|%21.42u|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[u]\t%s-->%s|%21.42u|\n", BOLD_GREEN, END, ULLONG_MAX);

	printf("\n%s----------------------------------------------------%s", LIGHT_GREY, END);
	printf("\n%s----------------------------------------------------%s\n\n", LIGHT_GREY, END);

	printf("\t\t\t->[ %s%%U%s ]<-\n", BOLD_LIGHT_GREY, END);
	printf("\t\t\t[ %sBASIC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][U]\t%s-->%s|%U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%U|\n", BOLD_RED, END, ULONG_MAX);
	ft_printf("\t[U]\t%s-->%s|%U|\n", BOLD_GREEN, END, ULONG_MAX);
	printf("[printf][U]\t%s-->%s|%U|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[U]\t%s-->%s|%U|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("[printf][U]\t%s-->%s|%U|\n", BOLD_RED, END, 0);
	ft_printf("\t[U]\t%s-->%s|%U|\n", BOLD_GREEN, END, 0);
	printf("\t\t\t[ %sMODIF%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][hU]\t%s-->%s|%hU|\n", BOLD_RED, END, USHRT_MAX);
	ft_printf("\t[hU]\t%s-->%s|%hU|\n", BOLD_GREEN, END, USHRT_MAX);
	printf("[printf][hhU]\t%s-->%s|%hhU|\n", BOLD_RED, END, UCHAR_MAX);
	ft_printf("\t[hhU]\t%s-->%s|%hhU|\n", BOLD_GREEN, END, UCHAR_MAX);
	printf("[printf][hhU]\t%s-->%s|%hhU|\n", BOLD_RED, END, UINT_MAX);
	ft_printf("\t[hhU]\t%s-->%s|%hhU|\n", BOLD_GREEN, END, UINT_MAX);
	printf("[printf][lU]\t%s-->%s|%lU|\n", BOLD_RED, END, ULONG_MAX);
	ft_printf("\t[lU]\t%s-->%s|%lU|\n", BOLD_GREEN, END, ULONG_MAX);
	printf("[printf][llU]\t%s-->%s|%llU|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[llU]\t%s-->%s|%llU|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t\t[ %s.PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][U]\t%s-->%s|%.0U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%.0U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%.1U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%.1U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%.0U|\n", BOLD_RED, END, 0);
	ft_printf("\t[U]\t%s-->%s|%.0U|\n", BOLD_GREEN, END, 0);
	printf("[printf][U]\t%s-->%s|%.1U|\n", BOLD_RED, END, 0);
	ft_printf("\t[U]\t%s-->%s|%.1U|\n", BOLD_GREEN, END, 0);
	printf("[printf][U]\t%s-->%s|%.7U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%.7U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%.21U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%.21U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%.21U|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[U]\t%s-->%s|%.21U|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t\t[ %sWIDTH%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][U]\t%s-->%s|%2U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%2U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%14U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%14U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%2U|\n", BOLD_RED, END, 0);
	ft_printf("\t[U]\t%s-->%s|%2U|\n", BOLD_GREEN, END, 0);
	printf("[printf][U]\t%s-->%s|%9U|\n", BOLD_RED, END, 0);
	ft_printf("\t[U]\t%s-->%s|%9U|\n", BOLD_GREEN, END, 0);
	printf("[printf][U]\t%s-->%s|%7U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%7U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%21U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%21U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%16U|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[U]\t%s-->%s|%16U|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t     [ %sWIDTH + .PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][U]\t%s-->%s|%1.0U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%1.0U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%10.1U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%10.1U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%1.1U|\n", BOLD_RED, END, 0);
	ft_printf("\t[U]\t%s-->%s|%1.1U|\n", BOLD_GREEN, END, 0);
	printf("[printf][U]\t%s-->%s|%10.2U|\n", BOLD_RED, END, 0);
	ft_printf("\t[U]\t%s-->%s|%10.2U|\n", BOLD_GREEN, END, 0);
	printf("[printf][U]\t%s-->%s|%7.4U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%7.4U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%42.21U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%42.21U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%21.7U|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[U]\t%s-->%s|%21.7U|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("[printf][U]\t%s-->%s|%10.21U|\n", BOLD_RED, END, 42);
	ft_printf("\t[U]\t%s-->%s|%10.21U|\n", BOLD_GREEN, END, 42);
	printf("[printf][U]\t%s-->%s|%21.42U|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[U]\t%s-->%s|%21.42U|\n", BOLD_GREEN, END, ULLONG_MAX);

	printf("\n%s----------------------------------------------------%s", LIGHT_GREY, END);
	printf("\n%s----------------------------------------------------%s\n\n", LIGHT_GREY, END);

	printf("\t\t\t->[ %s%%o%s ]<-\n", BOLD_LIGHT_GREY, END);
	printf("\t\t\t[ %sBASIC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][o]\t%s-->%s|%o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%o|\n", BOLD_RED, END, 0);
	ft_printf("\t[o]\t%s-->%s|%o|\n", BOLD_GREEN, END, 0);
	printf("[printf][o]\t%s-->%s|%o|\n", BOLD_RED, END, UINT_MAX);
	ft_printf("\t[o]\t%s-->%s|%o|\n", BOLD_GREEN, END, UINT_MAX);
	printf("\t\t\t[ %sMODIF%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][ho]\t%s-->%s|%ho|\n", BOLD_RED, END, USHRT_MAX);
	ft_printf("\t[ho]\t%s-->%s|%ho|\n", BOLD_GREEN, END, USHRT_MAX);
	printf("[printf][hho]\t%s-->%s|%hho|\n", BOLD_RED, END, UCHAR_MAX);
	ft_printf("\t[hho]\t%s-->%s|%hho|\n", BOLD_GREEN, END, UCHAR_MAX);
	printf("[printf][hho]\t%s-->%s|%hho|\n", BOLD_RED, END, UINT_MAX);
	ft_printf("\t[hho]\t%s-->%s|%hho|\n", BOLD_GREEN, END, UINT_MAX);
	printf("[printf][lo]\t%s-->%s|%lo|\n", BOLD_RED, END, ULONG_MAX);
	ft_printf("\t[lo]\t%s-->%s|%lo|\n", BOLD_GREEN, END, ULONG_MAX);
	printf("[printf][llo]\t%s-->%s|%llo|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[llo]\t%s-->%s|%llo|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t\t[ %s.PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][o]\t%s-->%s|%.0o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%.0o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%.1o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%.1o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%.0o|\n", BOLD_RED, END, 0);
	ft_printf("\t[o]\t%s-->%s|%.0o|\n", BOLD_GREEN, END, 0);
	printf("[printf][o]\t%s-->%s|%.1o|\n", BOLD_RED, END, 0);
	ft_printf("\t[o]\t%s-->%s|%.1o|\n", BOLD_GREEN, END, 0);
	printf("[printf][o]\t%s-->%s|%.7o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%.7o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%.21o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%.21o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%.21o|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[o]\t%s-->%s|%.21o|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t\t[ %sWIDTH%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][o]\t%s-->%s|%2o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%2o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%14o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%14o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%2o|\n", BOLD_RED, END, 0);
	ft_printf("\t[o]\t%s-->%s|%2o|\n", BOLD_GREEN, END, 0);
	printf("[printf][o]\t%s-->%s|%9o|\n", BOLD_RED, END, 0);
	ft_printf("\t[o]\t%s-->%s|%9o|\n", BOLD_GREEN, END, 0);
	printf("[printf][o]\t%s-->%s|%17o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%17o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%21o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%21o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%16o|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[o]\t%s-->%s|%16o|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t     [ %sWIDTH + .PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][o]\t%s-->%s|%1.0o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%1.0o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%10.1o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%10.1o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%1.1o|\n", BOLD_RED, END, 0);
	ft_printf("\t[o]\t%s-->%s|%1.1o|\n", BOLD_GREEN, END, 0);
	printf("[printf][o]\t%s-->%s|%10.2o|\n", BOLD_RED, END, 0);
	ft_printf("\t[o]\t%s-->%s|%10.2o|\n", BOLD_GREEN, END, 0);
	printf("[printf][o]\t%s-->%s|%7.4o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%7.4o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%42.21o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%42.21o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%21.7o|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[o]\t%s-->%s|%21.7o|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("[printf][o]\t%s-->%s|%10.21o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%10.21o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%21.42o|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[o]\t%s-->%s|%21.42o|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t\t[ %sFLAG #%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][o]\t%s-->%s|%#o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%#o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%#o|\n", BOLD_RED, END, 0);
	ft_printf("\t[o]\t%s-->%s|%#o|\n", BOLD_GREEN, END, 0);
	printf("[printf][o]\t%s-->%s|%#10o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%#10o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%#.7o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%#.7o|\n", BOLD_GREEN, END, 42);
	printf("[printf][o]\t%s-->%s|%#42.21o|\n", BOLD_RED, END, 42);
	ft_printf("\t[o]\t%s-->%s|%#42.21o|\n", BOLD_GREEN, END, 42);

	printf("\n%s----------------------------------------------------%s", LIGHT_GREY, END);
	printf("\n%s----------------------------------------------------%s\n\n", LIGHT_GREY, END);

	printf("\t\t\t->[ %s%%O%s ]<-\n", BOLD_LIGHT_GREY, END);
	printf("\t\t\t[ %sBASIC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][O]\t%s-->%s|%O|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%O|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%O|\n", BOLD_RED, END, 0);
	ft_printf("\t[O]\t%s-->%s|%O|\n", BOLD_GREEN, END, 0);
	printf("[printf][O]\t%s-->%s|%O|\n", BOLD_RED, END, ULONG_MAX);
	ft_printf("\t[O]\t%s-->%s|%O|\n", BOLD_GREEN, END, ULONG_MAX);
	printf("\t\t\t[ %sMODIF%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][hO]\t%s-->%s|%hO|\n", BOLD_RED, END, USHRT_MAX);
	ft_printf("\t[hO]\t%s-->%s|%hO|\n", BOLD_GREEN, END, USHRT_MAX);
	printf("[printf][hhO]\t%s-->%s|%hhO|\n", BOLD_RED, END, UCHAR_MAX);
	ft_printf("\t[hhO]\t%s-->%s|%hhO|\n", BOLD_GREEN, END, UCHAR_MAX);
	printf("[printf][hhO]\t%s-->%s|%hhO|\n", BOLD_RED, END, UINT_MAX);
	ft_printf("\t[hhO]\t%s-->%s|%hhO|\n", BOLD_GREEN, END, UINT_MAX);
	printf("[printf][lO]\t%s-->%s|%lO|\n", BOLD_RED, END, ULONG_MAX);
	ft_printf("\t[lO]\t%s-->%s|%lO|\n", BOLD_GREEN, END, ULONG_MAX);
	printf("[printf][llO]\t%s-->%s|%llO|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[llO]\t%s-->%s|%llO|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t\t[ %s.PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][O]\t%s-->%s|%.0O|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%.0O|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%.6O|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%.6O|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%.0O|\n", BOLD_RED, END, 0);
	ft_printf("\t[O]\t%s-->%s|%.0O|\n", BOLD_GREEN, END, 0);
	printf("[printf][O]\t%s-->%s|%.8O|\n", BOLD_RED, END, 0);
	ft_printf("\t[O]\t%s-->%s|%.8O|\n", BOLD_GREEN, END, 0);
	printf("[printf][O]\t%s-->%s|%.7O|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%.7O|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%.21O|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%.21O|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%.21O|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[O]\t%s-->%s|%.21O|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t\t[ %sWIDTH%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][O]\t%s-->%s|%2O|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%2O|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%14O|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%14O|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%3O|\n", BOLD_RED, END, 0);
	ft_printf("\t[O]\t%s-->%s|%3O|\n", BOLD_GREEN, END, 0);
	printf("[printf][O]\t%s-->%s|%9O|\n", BOLD_RED, END, 0);
	ft_printf("\t[O]\t%s-->%s|%9O|\n", BOLD_GREEN, END, 0);
	printf("[printf][O]\t%s-->%s|%17O|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%17O|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%21O|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%21O|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%16O|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[O]\t%s-->%s|%16O|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("\t\t     [ %sWIDTH + .PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][O]\t%s-->%s|%1.0o|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%1.0o|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%10.1o|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%10.1o|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%1.1o|\n", BOLD_RED, END, 0);
	ft_printf("\t[O]\t%s-->%s|%1.1o|\n", BOLD_GREEN, END, 0);
	printf("[printf][O]\t%s-->%s|%10.2o|\n", BOLD_RED, END, 0);
	ft_printf("\t[O]\t%s-->%s|%10.2o|\n", BOLD_GREEN, END, 0);
	printf("[printf][O]\t%s-->%s|%7.4o|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%7.4o|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%42.21o|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%42.21o|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%21.7o|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[O]\t%s-->%s|%21.7o|\n", BOLD_GREEN, END, ULLONG_MAX);
	printf("[printf][O]\t%s-->%s|%10.21o|\n", BOLD_RED, END, 42);
	ft_printf("\t[O]\t%s-->%s|%10.21o|\n", BOLD_GREEN, END, 42);
	printf("[printf][O]\t%s-->%s|%42.21o|\n", BOLD_RED, END, ULLONG_MAX);
	ft_printf("\t[O]\t%s-->%s|%42.21o|\n", BOLD_GREEN, END, ULLONG_MAX);

	printf("\n%s----------------------------------------------------%s", LIGHT_GREY, END);
	printf("\n%s----------------------------------------------------%s\n\n", LIGHT_GREY, END);

	printf("\t\t\t->[ %s%%x%s ]<-\n", BOLD_LIGHT_GREY, END);
	printf("\t\t\t[ %sBASIC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][x]\t%s-->%s|%x|\n", BOLD_RED, END, 42);
	ft_printf("\t[x]\t%s-->%s|%x|\n", BOLD_GREEN, END, 42);
	printf("[printf][x]\t%s-->%s|%x|\n", BOLD_RED, END, 2142);
	ft_printf("\t[x]\t%s-->%s|%x|\n", BOLD_GREEN, END, 2142);
	printf("[printf][x]\t%s-->%s|%x|\n", BOLD_RED, END, 0);
	ft_printf("\t[x]\t%s-->%s|%x|\n", BOLD_GREEN, END, 0);
	printf("[printf][x]\t%s-->%s|%x|\n", BOLD_RED, END, UINT_MAX);
	ft_printf("\t[x]\t%s-->%s|%x|\n", BOLD_GREEN, END, UINT_MAX);
	printf("\t\t\t[ %sMODIF%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][hx]\t%s-->%s|%hx|\n", BOLD_RED, END, USHRT_MAX);
	ft_printf("\t[hx]\t%s-->%s|%hx|\n", BOLD_GREEN, END, USHRT_MAX);
	printf("[printf][hhx]\t%s-->%s|%hhx|\n", BOLD_RED, END, UCHAR_MAX);
	ft_printf("\t[hhx]\t%s-->%s|%hhx|\n", BOLD_GREEN, END, UCHAR_MAX);
	printf("[printf][hhx]\t%s-->%s|%hhx|\n", BOLD_RED, END, (UINT_MAX - 4500));
	ft_printf("\t[hhx]\t%s-->%s|%hhx|\n", BOLD_GREEN, END, (UINT_MAX - 4500));
	printf("[printf][lx]\t%s-->%s|%lx|\n", BOLD_RED, END, (ULONG_MAX / 3) - 42);
	ft_printf("\t[lx]\t%s-->%s|%lx|\n", BOLD_GREEN, END, (ULONG_MAX / 3) - 42);
	printf("[printf][llx]\t%s-->%s|%llx|\n", BOLD_RED, END, (ULLONG_MAX - 42));
	ft_printf("\t[llx]\t%s-->%s|%llx|\n", BOLD_GREEN, END, (ULLONG_MAX - 42));
	printf("\t\t\t[ %s.PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][x]\t%s-->%s|%.0x|\n", BOLD_RED, END, 42);
	ft_printf("\t[x]\t%s-->%s|%.0x|\n", BOLD_GREEN, END, 42);
	printf("[printf][x]\t%s-->%s|%.6x|\n", BOLD_RED, END, 42);
	ft_printf("\t[x]\t%s-->%s|%.6x|\n", BOLD_GREEN, END, 42);
	printf("[printf][x]\t%s-->%s|%.0x|\n", BOLD_RED, END, 0);
	ft_printf("\t[x]\t%s-->%s|%.0x|\n", BOLD_GREEN, END, 0);
	printf("[printf][x]\t%s-->%s|%.8x|\n", BOLD_RED, END, 0);
	ft_printf("\t[x]\t%s-->%s|%.8x|\n", BOLD_GREEN, END, 0);
	printf("[printf][x]\t%s-->%s|%.7x|\n", BOLD_RED, END, 42);
	ft_printf("\t[x]\t%s-->%s|%.7x|\n", BOLD_GREEN, END, 42);
	printf("[printf][x]\t%s-->%s|%.21x|\n", BOLD_RED, END, 42);
	ft_printf("\t[x]\t%s-->%s|%.21x|\n", BOLD_GREEN, END, 42);
	printf("[printf][x]\t%s-->%s|%.21x|\n", BOLD_RED, END, (UINT_MAX / 4));
	ft_printf("\t[x]\t%s-->%s|%.21x|\n", BOLD_GREEN, END, (UINT_MAX / 4));
	printf("\t\t     [ %sWIDTH + .PREC%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][x]\t%s-->%s|%1.0x|\n", BOLD_RED, END, 42);
	ft_printf("\t[x]\t%s-->%s|%1.0x|\n", BOLD_GREEN, END, 42);
	printf("[printf][x]\t%s-->%s|%10.1x|\n", BOLD_RED, END, 42);
	ft_printf("\t[x]\t%s-->%s|%10.1x|\n", BOLD_GREEN, END, 42);
	printf("[printf][x]\t%s-->%s|%1.1x|\n", BOLD_RED, END, 0);
	ft_printf("\t[x]\t%s-->%s|%1.1x|\n", BOLD_GREEN, END, 0);
	printf("[printf][x]\t%s-->%s|%10.2x|\n", BOLD_RED, END, 0);
	ft_printf("\t[x]\t%s-->%s|%10.2x|\n", BOLD_GREEN, END, 0);
	printf("[printf][x]\t%s-->%s|%7.4x|\n", BOLD_RED, END, 42);
	ft_printf("\t[x]\t%s-->%s|%7.4x|\n", BOLD_GREEN, END, 42);
	printf("[printf][x]\t%s-->%s|%42.21x|\n", BOLD_RED, END, 42);
	ft_printf("\t[x]\t%s-->%s|%42.21x|\n", BOLD_GREEN, END, 42);
	printf("[printf][x]\t%s-->%s|%21.7x|\n", BOLD_RED, END, UINT_MAX);
	ft_printf("\t[x]\t%s-->%s|%21.7x|\n", BOLD_GREEN, END, UINT_MAX);
	printf("[printf][x]\t%s-->%s|%10.21x|\n", BOLD_RED, END, 42);
	ft_printf("\t[x]\t%s-->%s|%10.21x|\n", BOLD_GREEN, END, 42);
	printf("[printf][x]\t%s-->%s|%42.21x|\n", BOLD_RED, END, UINT_MAX);
	ft_printf("\t[x]\t%s-->%s|%42.21x|\n", BOLD_GREEN, END, UINT_MAX);

	printf("\n%s----------------------------------------------------%s", LIGHT_GREY, END);
	printf("\n%s----------------------------------------------------%s\n\n", LIGHT_GREY, END);

	printf("\t\t\t->[ %s%%%s ]<-\n", BOLD_LIGHT_GREY, END);
	printf("\t\t\t[ %sOTHERS%s ]\n", RED, END);
	printf("\t\t%s***************************%s\n", BOLD_BLACK, END);
	printf("[printf][.]\t%s-->%s|%%|\n", BOLD_RED, END);
	ft_printf("\t[.]\t%s-->%s|%%|\n", BOLD_GREEN, END);
	printf("[printf][.]\t%s-->%s|with %% string|\n", BOLD_RED, END);
	ft_printf("\t[.]\t%s-->%s|with %% string|\n", BOLD_GREEN, END);*/
	/*printf("\n   |o|o|o|*****************************************|o|o|o|\n\n");

	printf("\t\t--->[ %%x ]<---\n");
	printf("\t\t--->[ %%x ]<---\n");
	printf("\t\t [ simple test ]\n");
	printf("\t*********************************\n");
	printf("\t*********************************\n");
	printf("[printf][x]\t-->|%x|\n", 42);
	ft_printf("\t[x]\t-->|%x|\n", 42);
	printf("[printf][x]\t-->|%o|\n", UINT_MAX);
	ft_printf("\t[x]\t-->|%o|\n", UINT_MAX);
	printf("[printf][x]\t-->|[%x]-[%x]-[%x]|\n", 42, 21, UINT_MAX);
	ft_printf("\t[x]\t-->|[%x]-[%x]-[%x]|\n", 42, 21, UINT_MAX);

	printf("\n   |o|o|o|*****************************************|o|o|o|\n\n");

	printf("\t\t--->[ %%X ]<---\n");
	printf("\t\t--->[ %%X ]<---\n");
	printf("\t\t [ simple test ]\n");
	printf("\t*********************************\n");
	printf("\t*********************************\n");
	printf("[printf][X]\t-->|%X|\n", 42);
	ft_printf("\t[x]\t-->|%X|\n", 42);
	printf("[printf][X]\t-->|%X|\n", UINT_MAX);
	ft_printf("\t[X]\t-->|%X|\n", UINT_MAX);
	printf("[printf][X]\t-->|[%X]-[%X]-[%X]|\n", 42, 21, UINT_MAX);
	ft_printf("\t[X]\t-->|[%X]-[%X]-[%X]|\n", 42, 21, UINT_MAX);

	printf("\n   |o|o|o|*****************************************|o|o|o|\n\n");

	printf("\t\t--->[ oth ]<---\n");
	printf("\t\t--->[\033[31mOTHERS\033[0m]<---\n");
	printf("\t\t [ simple test ]\n");
	printf("\t*********************************\n");
	printf("\t*********************************\n");
	printf("[printf][oth]\t-->|%%|\n");
	ft_printf("\t[oth]\t-->|%%|\n");
	printf("[printf][oth]\t-->|aa%%bb|\n");
	ft_printf("\t[oth]\t-->|aa%%bb|\n");

	printf("\n   |o|o|o|*****************************************|o|o|o|\n\n");

	printf("\t\t [ MULTI TEST ]\n");
	printf("\t*********************************\n");
	printf("\t*********************************\n");
	printf("[printf][.]\t-->|!!%s??%p??%d!!|\n", "string", &i, 42);
	ft_printf("\t[.]\t-->|!!%s??%p??%d!!|\n", "string", &i, 42);
	printf("[printf][..]\t-->|!!%d??%s??%p!!|\n", 21, "babaAuWhum", &str);
	ft_printf("\t[..]\t-->|!!%d??%s??%p!!|\n", 21, "babaAuWhum", &str);*/
//	ft_printf("{%03c}", 'h');
/*	printf("{%#.5x}\n", 0);
	ft_printf("{%#.5x}\n", 0);
	ft_printf("{%05.%}", 0);*/
	return (0);
}
